package com.uc_mobileapps.seifesample01.bo.schema;
import com.uc_mobileapps.seifesample01.bo.Customer;

import android.content.ContentResolver;
import android.content.ContentValues;
import android.content.Context;
import android.database.Cursor;
import android.net.Uri;
import java.util.List;
import java.util.ArrayList;

public class CustomerSchema { 
	//[begin seife autogenerated@

	/**
	 * Table name of the Customer table
	 */
	public static String TBL_CUSTOMER = "customer";
	

	/** 
	 * a simple primary key field
	 */
	public static String COL_ID = "id";

	public static String COL_NAME = "name";

	/** Fully qualified column name of {@link #COL_ID */
	public static String COL_ID_FQN = "customer.id";

	/** Fully qualified column name of {@link #COL_NAME */
	public static String COL_NAME_FQN = "customer.name";
	
	/**
	 * All columns
	 */
	public static String[] COLUMNS = new String[] { COL_ID, COL_NAME	};

	/**
	 * Table creation script
	 */
	public static final String SQL_CREATE_TABLE_CUSTOMER =
			"create table " + TBL_CUSTOMER + " (" +
					COL_ID + " integer primary key autoincrement," +
					COL_NAME + " text not null" +
					")";


 

	private static CustomerSchema schema = new CustomerSchema();
	public static CustomerSchema instance() {
		return schema;
	}

	/**
	 * Checks for mandatory constraints defined on fields
	 */
	public boolean checkConstraints(ContentValues contentValues) {
		return true;
	}
	
	/**
	 * Gets all attribute values of the bo as key value pairs
	 * @param bo may not be null
	 * @return new instance of {@link ContentValues}
	 */
	public ContentValues getContentValues(Customer bo) {
		ContentValues contentValues = new ContentValues();

		if (bo.getId() != null) {
			contentValues.put(COL_ID, bo.getId());
		}
		contentValues.put(COL_NAME, bo.getName());
		return contentValues;
	}

	/**
	 * Sets all attributes from the cursor
	 * @param cursorFrom the cursor to read from
	 * @param bo may be null
	 * @return the bo passed as a parameter or a new instance
	 */
	public Customer readFromCursor(Cursor cursorFrom, Customer bo)
	{
		if (bo == null) {
			bo = new Customer();
		}
		final Cursor c = cursorFrom; 

		bo.setId(c.isNull(c.getColumnIndex(COL_ID)) ? null : c.getLong(c.getColumnIndex(COL_ID)));
		bo.setName(c.getString(c.getColumnIndex(COL_NAME)));
		return bo;
	}
	
	
	/**
	 * @return hard-coded table creation and index scripts
	 */
	public List<String> getTableScripts() {
		List<String> result = new ArrayList<String>();
		result.add(SQL_CREATE_TABLE_CUSTOMER); 
		return result;
	}

 
	//@end seife autogenerated]



	
}
