/**
 * 
 */
package com.uc_mobileapps.tests.sqlite.provider;

import android.content.ContentProvider;
import android.content.ContentResolver;
import android.content.ContentUris;
import android.content.ContentValues;
import android.content.UriMatcher;
import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteQueryBuilder;
import android.net.Uri;

import com.uc_mobileapps.tests.sqlite.bo.AdvancedTypes;
import com.uc_mobileapps.tests.sqlite.bo.CommonTypes;
import com.uc_mobileapps.tests.sqlite.bo.Version1;
import com.uc_mobileapps.tests.sqlite.bo.Version2;
import com.uc_mobileapps.tests.sqlite.bo.schema.AdvancedTypesSchema;
import com.uc_mobileapps.tests.sqlite.bo.schema.CommonTypesSchema;
import com.uc_mobileapps.tests.sqlite.bo.schema.Version1Schema;
import com.uc_mobileapps.tests.sqlite.bo.schema.Version2Schema;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import com.uc_mobileapps.tests.sqlite.db.GeneralTestsDBOpenHelper;

/**
 * Content provider implementation for com.uc_mobileapps.tests.sqlite.bo.CommonTypes * @author ${properties.author}
 */
public class GeneralTestsProvider extends ContentProvider {

	/**
	 * Pass a query limit to the provider
	 */
	public static final String QUERY_PARAMETER_LIMIT = "_limit";

	/**
	 * Pass a having clause to the provider
	 */
	public static final String QUERY_PARAMETER_HAVING = "_having";

	/**
	 * Pass a group by to the provider
	 */
	public static final String QUERY_PARAMETER_GROUP_BY = "_groupby";


	/* (non-Javadoc)
	 * @see android.content.ContentProvider#onCreate()
	 */
	@Override
	public boolean onCreate() {
		if (!seifeCreate()) {
			return false;
		}
		return true;
	}

	//[begin seife autogenerated@
	
	/**
	 * Content-Provider Authority for Uris (is in the demo package for historical reasons)
	 */
	public static final String AUTHORITY = "com.uc_mobileapps.tests.sqlite.provider";

	/**
	 * Better don't use this directly, use {@link #getContentUriVersion2()} instead
	 */
	public static Uri CONTENT_URI_VERSION2 = Uri.parse("content://" + AUTHORITY + "/" + Version2Schema.TBL_VERSION2);

	/**
	 * Better don't use this directly, use {@link #getContentUriAdvancedTypes()} instead
	 */
	public static Uri CONTENT_URI_ADVANCED_TYPES = Uri.parse("content://" + AUTHORITY + "/" + AdvancedTypesSchema.TBL_ADVANCED_TYPES);

	/**
	 * Better don't use this directly, use {@link #getContentUriVersion1()} instead
	 */
	public static Uri CONTENT_URI_VERSION1 = Uri.parse("content://" + AUTHORITY + "/" + Version1Schema.TBL_VERSION1);

	/**
	 * Better don't use this directly, use {@link #getContentUriCommonTypes()} instead
	 */
	public static Uri CONTENT_URI_COMMON_TYPES = Uri.parse("content://" + AUTHORITY + "/" + CommonTypesSchema.TBL_COMMON_TYPES);

	/**
	 * Uri for com.uc_mobileapps.tests.sqlite.bo.Version2
	 */
	public static Uri getContentUriVersion2() {
		return CONTENT_URI_VERSION2;
	}
	
	/**
	 * Explicit URI configuration
	 */
	public static void setContentUriVersion2(Uri uri) {
		CONTENT_URI_VERSION2 = uri;
	}

	/**
	 * Uri for com.uc_mobileapps.tests.sqlite.bo.AdvancedTypes
	 */
	public static Uri getContentUriAdvancedTypes() {
		return CONTENT_URI_ADVANCED_TYPES;
	}
	
	/**
	 * Explicit URI configuration
	 */
	public static void setContentUriAdvancedTypes(Uri uri) {
		CONTENT_URI_ADVANCED_TYPES = uri;
	}

	/**
	 * Uri for com.uc_mobileapps.tests.sqlite.bo.Version1
	 */
	public static Uri getContentUriVersion1() {
		return CONTENT_URI_VERSION1;
	}
	
	/**
	 * Explicit URI configuration
	 */
	public static void setContentUriVersion1(Uri uri) {
		CONTENT_URI_VERSION1 = uri;
	}

	/**
	 * Uri for com.uc_mobileapps.tests.sqlite.bo.CommonTypes
	 */
	public static Uri getContentUriCommonTypes() {
		return CONTENT_URI_COMMON_TYPES;
	}
	
	/**
	 * Explicit URI configuration
	 */
	public static void setContentUriCommonTypes(Uri uri) {
		CONTENT_URI_COMMON_TYPES = uri;
	}


	/**
	 * Code for urimatcher of the content provider
	 */
	protected static final int URI_CODE_VERSION2 = 0;
	/**
	 * Version2 by id uri
	 */
	protected static final int URI_CODE_VERSION2_ID = 1;

	/**
	 * Version2 for batch updates
	 */
	protected static final int URI_CODE_VERSION2_NO_NOTIFY_ID = 2;

	/**
	 * Code for urimatcher of the content provider
	 */
	protected static final int URI_CODE_ADVANCED_TYPES = 3;
	/**
	 * AdvancedTypes by id uri
	 */
	protected static final int URI_CODE_ADVANCED_TYPES_ID = 4;

	/**
	 * AdvancedTypes for batch updates
	 */
	protected static final int URI_CODE_ADVANCED_TYPES_NO_NOTIFY_ID = 5;

	/**
	 * Code for urimatcher of the content provider
	 */
	protected static final int URI_CODE_VERSION1 = 6;
	/**
	 * Version1 by id uri
	 */
	protected static final int URI_CODE_VERSION1_ID = 7;

	/**
	 * Version1 for batch updates
	 */
	protected static final int URI_CODE_VERSION1_NO_NOTIFY_ID = 8;

	/**
	 * Code for urimatcher of the content provider
	 */
	protected static final int URI_CODE_COMMON_TYPES = 9;
	/**
	 * CommonTypes by id uri
	 */
	protected static final int URI_CODE_COMMON_TYPES_ID = 10;

	/**
	 * CommonTypes for batch updates
	 */
	protected static final int URI_CODE_COMMON_TYPES_NO_NOTIFY_ID = 11;

	

	/**
	 * The database helper class where the table definitions reside
	 */
	private com.uc_mobileapps.tests.sqlite.db.GeneralTestsDBOpenHelper dbHelper;

	/**
	 * Autogenerated provider onCreate
	 * @see GeneralTestsProvider#onCreate()
	 */
	public boolean seifeCreate() {
		dbHelper = new com.uc_mobileapps.tests.sqlite.db.GeneralTestsDBOpenHelper(getContext());
		return true;
	}

	/**
	 * Uri Matcher of the content provider
	 */
	private UriMatcher uriMatcher;

	/**
	 * @return
	 */
	protected UriMatcher getUriMatcher() {
		if (uriMatcher == null) {
			uriMatcher = new UriMatcher(UriMatcher.NO_MATCH);
 			uriMatcher.addURI(AUTHORITY, Version2Schema.TBL_VERSION2, URI_CODE_VERSION2);
			uriMatcher.addURI(AUTHORITY, Version2Schema.TBL_VERSION2 + "/#", URI_CODE_VERSION2_ID);
			uriMatcher.addURI(AUTHORITY, Version2Schema.TBL_VERSION2 + "/batch/#", URI_CODE_VERSION2_NO_NOTIFY_ID);
  			uriMatcher.addURI(AUTHORITY, AdvancedTypesSchema.TBL_ADVANCED_TYPES, URI_CODE_ADVANCED_TYPES);
			uriMatcher.addURI(AUTHORITY, AdvancedTypesSchema.TBL_ADVANCED_TYPES + "/#", URI_CODE_ADVANCED_TYPES_ID);
			uriMatcher.addURI(AUTHORITY, AdvancedTypesSchema.TBL_ADVANCED_TYPES + "/batch/#", URI_CODE_ADVANCED_TYPES_NO_NOTIFY_ID);
  			uriMatcher.addURI(AUTHORITY, Version1Schema.TBL_VERSION1, URI_CODE_VERSION1);
			uriMatcher.addURI(AUTHORITY, Version1Schema.TBL_VERSION1 + "/#", URI_CODE_VERSION1_ID);
			uriMatcher.addURI(AUTHORITY, Version1Schema.TBL_VERSION1 + "/batch/#", URI_CODE_VERSION1_NO_NOTIFY_ID);
  			uriMatcher.addURI(AUTHORITY, CommonTypesSchema.TBL_COMMON_TYPES, URI_CODE_COMMON_TYPES);
			uriMatcher.addURI(AUTHORITY, CommonTypesSchema.TBL_COMMON_TYPES + "/#", URI_CODE_COMMON_TYPES_ID);
			uriMatcher.addURI(AUTHORITY, CommonTypesSchema.TBL_COMMON_TYPES + "/batch/#", URI_CODE_COMMON_TYPES_NO_NOTIFY_ID);
  		}
		return uriMatcher;
	}
	
	/**
	 * (non-Javadoc)
	 */
	@Override
	public String getType(Uri uri) {
		switch (getUriMatcher().match(uri)) {
 
		case URI_CODE_VERSION2:
			return ContentResolver.CURSOR_DIR_BASE_TYPE + "/vnd." + Version2.class.getPackage() + "." + Version2Schema.TBL_VERSION2;
		case URI_CODE_VERSION2_ID:
			return ContentResolver.CURSOR_ITEM_BASE_TYPE + "/vnd." + Version2.class.getPackage() + "." + Version2Schema.TBL_VERSION2;
		case URI_CODE_VERSION2_NO_NOTIFY_ID:
			return ContentResolver.CURSOR_ITEM_BASE_TYPE + "/vnd." + Version2.class.getPackage() + "." + Version2Schema.TBL_VERSION2;
 
		case URI_CODE_ADVANCED_TYPES:
			return ContentResolver.CURSOR_DIR_BASE_TYPE + "/vnd." + AdvancedTypes.class.getPackage() + "." + AdvancedTypesSchema.TBL_ADVANCED_TYPES;
		case URI_CODE_ADVANCED_TYPES_ID:
			return ContentResolver.CURSOR_ITEM_BASE_TYPE + "/vnd." + AdvancedTypes.class.getPackage() + "." + AdvancedTypesSchema.TBL_ADVANCED_TYPES;
		case URI_CODE_ADVANCED_TYPES_NO_NOTIFY_ID:
			return ContentResolver.CURSOR_ITEM_BASE_TYPE + "/vnd." + AdvancedTypes.class.getPackage() + "." + AdvancedTypesSchema.TBL_ADVANCED_TYPES;
 
		case URI_CODE_VERSION1:
			return ContentResolver.CURSOR_DIR_BASE_TYPE + "/vnd." + Version1.class.getPackage() + "." + Version1Schema.TBL_VERSION1;
		case URI_CODE_VERSION1_ID:
			return ContentResolver.CURSOR_ITEM_BASE_TYPE + "/vnd." + Version1.class.getPackage() + "." + Version1Schema.TBL_VERSION1;
		case URI_CODE_VERSION1_NO_NOTIFY_ID:
			return ContentResolver.CURSOR_ITEM_BASE_TYPE + "/vnd." + Version1.class.getPackage() + "." + Version1Schema.TBL_VERSION1;
 
		case URI_CODE_COMMON_TYPES:
			return ContentResolver.CURSOR_DIR_BASE_TYPE + "/vnd." + CommonTypes.class.getPackage() + "." + CommonTypesSchema.TBL_COMMON_TYPES;
		case URI_CODE_COMMON_TYPES_ID:
			return ContentResolver.CURSOR_ITEM_BASE_TYPE + "/vnd." + CommonTypes.class.getPackage() + "." + CommonTypesSchema.TBL_COMMON_TYPES;
		case URI_CODE_COMMON_TYPES_NO_NOTIFY_ID:
			return ContentResolver.CURSOR_ITEM_BASE_TYPE + "/vnd." + CommonTypes.class.getPackage() + "." + CommonTypesSchema.TBL_COMMON_TYPES;
		}
		return null;
	}

	/**
	 * Inserts a new object to the database
	 * @return the uri of the created object, null if the mandatory check failed 
	 * @see android.content.ContentProvider\#insert(android.net.Uri, android.content.ContentValues)
	 */
	@Override
	public Uri insert(Uri uri, ContentValues values) {
		
		SQLiteDatabase db = dbHelper.getWritableDatabase();
		long rowId;
		switch (getUriMatcher().match(uri))
		{
		case URI_CODE_VERSION2:
			if (!Version2Schema.instance().checkConstraints(values)) {
				return null;
			}
			rowId = db.insert(Version2Schema.TBL_VERSION2, null, values);
			if (rowId > 0) {
				Uri resUri = ContentUris.withAppendedId(uri, rowId);
				getContext().getContentResolver().notifyChange(resUri, null);
				return resUri;
			}
			break;
		case URI_CODE_VERSION2_ID: //unimplemented since id is generated
			break;
		case URI_CODE_ADVANCED_TYPES:
			if (!AdvancedTypesSchema.instance().checkConstraints(values)) {
				return null;
			}
			rowId = db.insert(AdvancedTypesSchema.TBL_ADVANCED_TYPES, null, values);
			if (rowId > 0) {
				Uri resUri = ContentUris.withAppendedId(uri, rowId);
				getContext().getContentResolver().notifyChange(resUri, null);
				return resUri;
			}
			break;
		case URI_CODE_ADVANCED_TYPES_ID: //unimplemented since id is generated
			break;
		case URI_CODE_VERSION1:
			if (!Version1Schema.instance().checkConstraints(values)) {
				return null;
			}
			rowId = db.insert(Version1Schema.TBL_VERSION1, null, values);
			if (rowId > 0) {
				Uri resUri = ContentUris.withAppendedId(uri, rowId);
				getContext().getContentResolver().notifyChange(resUri, null);
				return resUri;
			}
			break;
		case URI_CODE_VERSION1_ID: //unimplemented since id is generated
			break;
		case URI_CODE_COMMON_TYPES:
			if (!CommonTypesSchema.instance().checkConstraints(values)) {
				return null;
			}
			rowId = db.insert(CommonTypesSchema.TBL_COMMON_TYPES, null, values);
			if (rowId > 0) {
				Uri resUri = ContentUris.withAppendedId(uri, rowId);
				getContext().getContentResolver().notifyChange(resUri, null);
				return resUri;
			}
			break;
		case URI_CODE_COMMON_TYPES_ID: //unimplemented since id is generated
			break;
		}
		return null;
	}

	/* (non-Javadoc)
	 * @see android.content.ContentProvider\#update(android.net.Uri, android.content.ContentValues, java.lang.String, java.lang.String[])
	 */
	@Override
	public int update(Uri uri, ContentValues values, String selection,
			String[] selectionArgs) 
	{
		int rowsAffected = 0;
		SQLiteDatabase db = dbHelper.getWritableDatabase();
		int matchId = getUriMatcher().match(uri);
		String[] primaryKey;
		switch (matchId)
		{
		case URI_CODE_VERSION2_ID:
		case URI_CODE_VERSION2_NO_NOTIFY_ID:
			primaryKey = new String[] { uri.getQueryParameter(Version2Schema.COL_ID) };
			rowsAffected = db.update(Version2Schema.TBL_VERSION2, values,  Version2Schema.COL_ID + " = ?" , primaryKey);
			break;
		case URI_CODE_ADVANCED_TYPES_ID:
		case URI_CODE_ADVANCED_TYPES_NO_NOTIFY_ID:
			primaryKey = new String[] { uri.getQueryParameter(AdvancedTypesSchema.COL_ID) };
			rowsAffected = db.update(AdvancedTypesSchema.TBL_ADVANCED_TYPES, values,  AdvancedTypesSchema.COL_ID + " = ?" , primaryKey);
			break;
		case URI_CODE_VERSION1_ID:
		case URI_CODE_VERSION1_NO_NOTIFY_ID:
			primaryKey = new String[] { uri.getQueryParameter(Version1Schema.COL_ID) };
			rowsAffected = db.update(Version1Schema.TBL_VERSION1, values,  Version1Schema.COL_ID + " = ?" , primaryKey);
			break;
		case URI_CODE_COMMON_TYPES_ID:
		case URI_CODE_COMMON_TYPES_NO_NOTIFY_ID:
			primaryKey = new String[] { uri.getQueryParameter(CommonTypesSchema.COL_ID) };
			rowsAffected = db.update(CommonTypesSchema.TBL_COMMON_TYPES, values,  CommonTypesSchema.COL_ID + " = ?" , primaryKey);
			break;
		default:
			break;
		}
		if (rowsAffected > 0) {
			switch (matchId) {
			case URI_CODE_VERSION2_ID:
			case URI_CODE_ADVANCED_TYPES_ID:
			case URI_CODE_VERSION1_ID:
			case URI_CODE_COMMON_TYPES_ID:
				getContext().getContentResolver().notifyChange(uri, null);			
				break;
			default: 
				break;
			}
		}	
		return rowsAffected;
	}
	
	/* (non-Javadoc)
	 * @see android.content.ContentProvider\#delete(android.net.Uri, java.lang.String, java.lang.String[])
	 */
	@Override
	public int delete(Uri uri, String selection, String[] selectionArgs) {
		int rowsAffected = 0;

		SQLiteDatabase db = dbHelper.getWritableDatabase();
		String[] primaryKey;
		int matchId = getUriMatcher().match(uri);
		switch (matchId)
		{
		case URI_CODE_VERSION2_ID:
		case URI_CODE_VERSION2_NO_NOTIFY_ID:
			primaryKey = new String[] { uri.getQueryParameter(Version2Schema.COL_ID) };
			rowsAffected = db.delete(Version2Schema.TBL_VERSION2,Version2Schema.COL_ID + " = ?" , primaryKey);
			if (rowsAffected > 0) {
				getContext().getContentResolver().notifyChange(uri, null);			
			}
			break;
		case URI_CODE_ADVANCED_TYPES_ID:
		case URI_CODE_ADVANCED_TYPES_NO_NOTIFY_ID:
			primaryKey = new String[] { uri.getQueryParameter(AdvancedTypesSchema.COL_ID) };
			rowsAffected = db.delete(AdvancedTypesSchema.TBL_ADVANCED_TYPES,AdvancedTypesSchema.COL_ID + " = ?" , primaryKey);
			if (rowsAffected > 0) {
				getContext().getContentResolver().notifyChange(uri, null);			
			}
			break;
		case URI_CODE_VERSION1_ID:
		case URI_CODE_VERSION1_NO_NOTIFY_ID:
			primaryKey = new String[] { uri.getQueryParameter(Version1Schema.COL_ID) };
			rowsAffected = db.delete(Version1Schema.TBL_VERSION1,Version1Schema.COL_ID + " = ?" , primaryKey);
			if (rowsAffected > 0) {
				getContext().getContentResolver().notifyChange(uri, null);			
			}
			break;
		case URI_CODE_COMMON_TYPES_ID:
		case URI_CODE_COMMON_TYPES_NO_NOTIFY_ID:
			primaryKey = new String[] { uri.getQueryParameter(CommonTypesSchema.COL_ID) };
			rowsAffected = db.delete(CommonTypesSchema.TBL_COMMON_TYPES,CommonTypesSchema.COL_ID + " = ?" , primaryKey);
			if (rowsAffected > 0) {
				getContext().getContentResolver().notifyChange(uri, null);			
			}
			break;
		default:
			break;
		}

		if (rowsAffected > 0) {
			switch (matchId) {
			case URI_CODE_VERSION2_ID:
			case URI_CODE_ADVANCED_TYPES_ID:
			case URI_CODE_VERSION1_ID:
			case URI_CODE_COMMON_TYPES_ID:
				getContext().getContentResolver().notifyChange(uri, null);			
				break;
			default: 
				break;
			}
		}
		return rowsAffected;
	}

	/* (non-Javadoc)
	 * @see android.content.ContentProvider\#query(android.net.Uri, java.lang.String[], java.lang.String, java.lang.String[], java.lang.String)
	 */
	@Override
	public Cursor query(Uri uri, String[] projection, String selectionParam,
			String[] selectionParamArgs, String sortOrder) {
		StringBuilder selection = new StringBuilder();;
		List<String> selectionArgs = new ArrayList<String>();
		
		String groupBy = uri.getQueryParameter(QUERY_PARAMETER_GROUP_BY);
		String having = uri.getQueryParameter(QUERY_PARAMETER_HAVING);
		String limit = uri.getQueryParameter(QUERY_PARAMETER_LIMIT);
		SQLiteQueryBuilder qb = new SQLiteQueryBuilder();

		int matchId = getUriMatcher().match(uri);
		switch (matchId) {
		case URI_CODE_VERSION2:
			qb.setTables(Version2Schema.TBL_VERSION2);
			if (selectionParam != null) {
				selection.append(selectionParam);
			}
			if (selectionParamArgs != null) {
				selectionArgs = Arrays.asList(selectionParamArgs);
			}
					break;
		case URI_CODE_VERSION2_ID:
		case URI_CODE_VERSION2_NO_NOTIFY_ID:
			qb.setTables(Version2Schema.TBL_VERSION2);
			selection
			.append(Version2Schema.COL_ID + " = ?");
						selectionArgs.add(uri.getQueryParameter(Version2Schema.COL_ID));
		break;
		case URI_CODE_ADVANCED_TYPES:
			qb.setTables(AdvancedTypesSchema.TBL_ADVANCED_TYPES);
			if (selectionParam != null) {
				selection.append(selectionParam);
			}
			if (selectionParamArgs != null) {
				selectionArgs = Arrays.asList(selectionParamArgs);
			}
					break;
		case URI_CODE_ADVANCED_TYPES_ID:
		case URI_CODE_ADVANCED_TYPES_NO_NOTIFY_ID:
			qb.setTables(AdvancedTypesSchema.TBL_ADVANCED_TYPES);
			selection
			.append(AdvancedTypesSchema.COL_ID + " = ?");
						selectionArgs.add(uri.getQueryParameter(AdvancedTypesSchema.COL_ID));
		break;
		case URI_CODE_VERSION1:
			qb.setTables(Version1Schema.TBL_VERSION1);
			if (selectionParam != null) {
				selection.append(selectionParam);
			}
			if (selectionParamArgs != null) {
				selectionArgs = Arrays.asList(selectionParamArgs);
			}
					break;
		case URI_CODE_VERSION1_ID:
		case URI_CODE_VERSION1_NO_NOTIFY_ID:
			qb.setTables(Version1Schema.TBL_VERSION1);
			selection
			.append(Version1Schema.COL_ID + " = ?");
						selectionArgs.add(uri.getQueryParameter(Version1Schema.COL_ID));
		break;
		case URI_CODE_COMMON_TYPES:
			qb.setTables(CommonTypesSchema.TBL_COMMON_TYPES);
			if (selectionParam != null) {
				selection.append(selectionParam);
			}
			if (selectionParamArgs != null) {
				selectionArgs = Arrays.asList(selectionParamArgs);
			}
					break;
		case URI_CODE_COMMON_TYPES_ID:
		case URI_CODE_COMMON_TYPES_NO_NOTIFY_ID:
			qb.setTables(CommonTypesSchema.TBL_COMMON_TYPES);
			selection
			.append(CommonTypesSchema.COL_ID + " = ?");
						selectionArgs.add(uri.getQueryParameter(CommonTypesSchema.COL_ID));
		break;
		default:
			return null;
		}
				Cursor c = qb.query(dbHelper.getReadableDatabase(), projection, selection.toString(), selectionArgs.toArray(new String[selectionArgs.size()]), groupBy, having, sortOrder, limit);

		c.setNotificationUri(getContext().getContentResolver(), uri);
		return c;
	}
	//@end seife autogenerated]



}
