package com.uc_mobileapps.tests.sqlite.bo.schema;
import android.content.ContentValues;
import android.database.Cursor;

import com.uc_mobileapps.tests.sqlite.bo.Version1;

import java.util.ArrayList;
import java.util.List;

import android.content.Context;
import android.os.Parcel;
import android.os.Parcelable;

public class Version1Schema { 
	//[begin seife autogenerated@

	/**
	 * Table name of the Version1 table
	 */
	public static String TBL_VERSION1 = "version1";
	

	public static String COL_ID = "id";

	public static String COL_ADDED_IN_V2 = "addedInV2";

	/** Fully qualified column name of {@link #COL_ID */
	public static String COL_ID_FQN = "version1.id";

	/** Fully qualified column name of {@link #COL_ADDED_IN_V2 */
	public static String COL_ADDED_IN_V2_FQN = "version1.addedInV2";
	
	/**
	 * All columns
	 */
	public static String[] COLUMNS = new String[] { COL_ID, COL_ADDED_IN_V2	};

	/**
	 * Table creation script
	 */
	public static final String SQL_CREATE_TABLE_VERSION1 =
			"create table " + TBL_VERSION1 + " (" +
					COL_ID + " integer primary key autoincrement," +
					COL_ADDED_IN_V2 + " text" +
					")";


 

	private static Version1Schema schema = new Version1Schema();
	public static Version1Schema instance() {
		return schema;
	}

	/**
	 * Checks for mandatory constraints defined on fields
	 */
	public boolean checkConstraints(ContentValues contentValues) {
		return true;
	}
	
	/**
	 * Gets all attribute values of the bo as key value pairs
	 * @param bo may not be null
	 * @return new instance of {@link ContentValues}
	 */
	public ContentValues getContentValues(Version1 bo) {
		ContentValues contentValues = new ContentValues();

		if (bo.getId() != null) {
			contentValues.put(COL_ID, bo.getId());
		}
		contentValues.put(COL_ADDED_IN_V2, bo.getAddedInV2());
		return contentValues;
	}

	/**
	 * Sets all attributes from the cursor
	 * @param cursorFrom the cursor to read from
	 * @param bo may be null
	 * @return the bo passed as a parameter or a new instance
	 */
	public Version1 readFromCursor(Cursor cursorFrom, Version1 bo)
	{
		if (bo == null) {
			bo = new Version1();
		}
		final Cursor c = cursorFrom; 

		bo.setId(c.isNull(c.getColumnIndex(COL_ID)) ? null : c.getLong(c.getColumnIndex(COL_ID)));
		bo.setAddedInV2(c.getString(c.getColumnIndex(COL_ADDED_IN_V2)));
		return bo;
	}
	
	
	/**
	 * @return hard-coded table creation and index scripts
	 */
	public List<String> getTableScripts() {
		List<String> result = new ArrayList<String>();
		result.add(SQL_CREATE_TABLE_VERSION1); 
		return result;
	}

 
	//@end seife autogenerated]


	
}
