package com.uc_mobileapps.tests.sqlite.bo;

import android.os.Parcel;
import android.os.Parcelable;

import com.weebmeister.seife.anno.GeneratorOption;
import com.weebmeister.seife.anno.SeifeClass;
import com.weebmeister.seife.anno.SeifeField;

import android.content.Context;

/**
 * Created by Klaus on 10.03.2017.
 */
@SeifeClass(
        generatorOptions = {
                GeneratorOption.BOCLASS_PARCELABLE, GeneratorOption.SCHEMA_PEER,
                GeneratorOption.DB_HELPER+"=GeneralTestsDBOpenHelper",
                GeneratorOption.DATA_PROVIDER+"=GeneralTestsProvider"
        })
public class Version1 implements Parcelable {

    @SeifeField(isPrimaryKey = true)
    private Long id;

    @SeifeField(version=2)
    private String addedInV2;


    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getAddedInV2() {
        return addedInV2;
    }

    public void setAddedInV2(String addedInV2) {
        this.addedInV2 = addedInV2;
    }
	//[begin seife autogenerated@


	public static final String PARCELABLE_NAME = "com.uc_mobileapps.tests.sqlite.bo.Version1";
	public static final Parcelable.Creator<Version1> CREATOR = new Parcelable.Creator<Version1>() {

		@Override
		public Version1 createFromParcel(Parcel source) 
		{
			Version1 instance = new Version1();
			instance.readFromParcel(source);
			return instance;
		}

		@Override
		public Version1[] newArray(int size) {
			return new Version1[size];
		}	
	};

	@Override
	public int describeContents() { //relevant to parcel filedescriptors only, leave zero
		return 0;
	}
	

	public void readFromParcel(Parcel source) {
		String s;
		s=source.readString(); setId((s!=null) ? Long.parseLong(s) : null);
		setAddedInV2(source.readString());
	}


	@Override
	public void writeToParcel(Parcel dest, int flags) {
		dest.writeString((getId()!=null) ? Long.toString(getId()) : null);
		dest.writeString(getAddedInV2());
	}
		//@end seife autogenerated]


}
