package com.uc_mobileapps.seifesample02.delivery.schema;
import com.uc_mobileapps.seifesample02.delivery.Product;

import android.content.ContentResolver;
import android.content.ContentValues;
import android.content.Context;
import android.database.Cursor;
import android.net.Uri;
import java.util.List;
import java.util.ArrayList;

import android.os.Parcel;
import android.os.Parcelable;

public class ProductSchema { 
	//[begin seife autogenerated@

	/**
	 * Table name of the Product table
	 */
	public static String TBL_PRODUCT = "product";
	

	public static String COL_ID = "id";

	/** Fully qualified column name of {@link #COL_ID */
	public static String COL_ID_FQN = "product.id";
	
	/**
	 * All columns
	 */
	public static String[] COLUMNS = new String[] { COL_ID	};

	/**
	 * Table creation script
	 */
	public static final String SQL_CREATE_TABLE_PRODUCT =
			"create table " + TBL_PRODUCT + " (" + 

					COL_ID + " integer primary key autoincrement" +
					")";


 

	private static ProductSchema schema = new ProductSchema();
	public static ProductSchema instance() {
		return schema;
	}

	/**
	 * Checks for mandatory constraints defined on fields
	 */
	public boolean checkConstraints(ContentValues contentValues) {
		return true;
	}
	
	/**
	 * Gets all attribute values of the bo as key value pairs
	 * @param bo may not be null
	 * @return new instance of {@link ContentValues}
	 */
	public ContentValues getContentValues(Product bo) {
		ContentValues contentValues = new ContentValues();

		if (bo.getId() != null) {
			contentValues.put(COL_ID, bo.getId());
		}
		return contentValues;
	}

	/**
	 * Sets all attributes from the cursor
	 * @param cursorFrom the cursor to read from
	 * @param bo may be null
	 * @return the bo passed as a parameter or a new instance
	 */
	public Product readFromCursor(Cursor cursorFrom, Product bo)
	{
		if (bo == null) {
			bo = new Product();
		}
		final Cursor c = cursorFrom; 

		bo.setId(c.isNull(c.getColumnIndex(COL_ID)) ? null : c.getLong(c.getColumnIndex(COL_ID)));
		return bo;
	}
	
	
	/**
	 * @return hard-coded table creation and index scripts
	 */
	public List<String> getTableScripts() {
		List<String> result = new ArrayList<String>();
		result.add(SQL_CREATE_TABLE_PRODUCT); 
		return result;
	}

 
	//@end seife autogenerated]

	
}
